import { describe, expect, it } from "vitest";

import { base64Url, base64UrlDecode, fromHex, utf8 } from "./encoding";
import { buildLocalIdentity, signAssertion } from "./certificate";
import {
  assertUsableSeed,
  deriveLocalKeyPair,
  jwkThumbprint,
  signJwt,
  subjectFor,
  verifyJwtSignature,
} from "./keys";

/**
 * The vectors below were generated by running the **desktop client's own
 * dependencies** against a fixed seed, not by running this implementation and
 * writing down what it said. That is the whole point of them: they fail if this
 * port drifts from the thing it has to agree with.
 *
 * If one of these ever changes, nobody's identity is recoverable on the other
 * client. Do not update a vector to make a test pass.
 */
const SEED = fromHex("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20");

const VECTORS = [
  {
    host: "localhost:5001",
    x: "fGBBk29fk_eIeUnOTtRYlQQMj6igTCNhVHFVNh2madI",
    y: "WvxzoNNZhFJhzX2cu-EzlZVWKxLpZEeonNKNRR90938",
    thumbprint: "dSyYQQnyj3T1aXHx0Yvwkcw1hirk_bgmWRDgkMxFu20",
  },
  {
    host: "gryt.chat",
    x: "1vL1mw_frGtwxgw2TJ8twTNjht6hP82YewogUVwxs0w",
    y: "BE8-_ios7EJY6VJL_ZC3tUKBLUetdvqEEVviB6Crm7M",
    thumbprint: "xqeNvgMm4ObHrXM2KKwLSguoSTx3YGoU_7RUN92cqP8",
  },
  {
    host: "192.168.1.42:5001",
    x: "oBMRlfCgBXyl8E70JFFMY_32Jhjroh7yW9-kGkJ-ms8",
    y: "1kyC0xPIIdzAqTeS6M96uyeTuzr1YI4d3yB7Sgn8EgY",
    thumbprint: "adXaHcZ-BQh4FuLboobjM5BBi__dEMbO6AJgy0dQnE4",
  },
];

describe("base64url", () => {
  it("round-trips every byte value, which `btoa` on a binary string does not", () => {
    const all = new Uint8Array(256);
    for (let i = 0; i < 256; i++) all[i] = i;
    expect(base64UrlDecode(base64Url(all))).toEqual(all);
  });

  it("is unpadded and uses the URL alphabet", () => {
    // 0xff 0xff 0xff would be "////" in standard base64.
    expect(base64Url(new Uint8Array([0xff, 0xff, 0xff]))).toBe("____");
    expect(base64Url(new Uint8Array([0x01]))).toBe("AQ");
    expect(base64Url(new Uint8Array([0x01, 0x02]))).toBe("AQI");
  });

  it("handles the empty case", () => {
    expect(base64Url(new Uint8Array(0))).toBe("");
    expect(base64UrlDecode("")).toEqual(new Uint8Array(0));
  });
});

describe("deriveLocalKeyPair", () => {
  it.each(VECTORS)(
    "derives the web client's key for $host",
    ({ host, x, y, thumbprint }) => {
      const { publicJwk } = deriveLocalKeyPair(SEED, host);
      expect(publicJwk.x).toBe(x);
      expect(publicJwk.y).toBe(y);
      expect(jwkThumbprint(publicJwk)).toBe(thumbprint);
    },
  );

  it("gives a different key per host, so one server cannot recognise you on another", () => {
    const a = deriveLocalKeyPair(SEED, "a.example");
    const b = deriveLocalKeyPair(SEED, "b.example");
    expect(a.publicJwk.x).not.toBe(b.publicJwk.x);
  });

  it("is deterministic", () => {
    const a = deriveLocalKeyPair(SEED, "gryt.chat");
    const b = deriveLocalKeyPair(SEED, "gryt.chat");
    expect(a.publicJwk).toEqual(b.publicJwk);
    expect(a.privateKey).toEqual(b.privateKey);
  });

  it("prefixes the subject with key:, which is what the server derives", () => {
    const { publicJwk } = deriveLocalKeyPair(SEED, "gryt.chat");
    expect(subjectFor(publicJwk)).toBe(`key:${VECTORS[1].thumbprint}`);
  });
});

describe("assertUsableSeed", () => {
  it("rejects the wrong length", () => {
    expect(() => assertUsableSeed(new Uint8Array(31))).toThrow(/32 bytes/);
  });

  it("rejects a single repeated byte, which is what a broken generator gives", () => {
    expect(() => assertUsableSeed(new Uint8Array(32))).toThrow(/generator is broken/);
    expect(() => assertUsableSeed(new Uint8Array(32).fill(7))).toThrow(/generator is broken/);
  });

  it("accepts a real one", () => {
    expect(() => assertUsableSeed(SEED)).not.toThrow();
  });
});

describe("signJwt", () => {
  it("produces three base64url parts with an ES256 header", () => {
    const { privateKey } = deriveLocalKeyPair(SEED, "gryt.chat");
    const jwt = signJwt({ iss: "key:x", aud: "gryt.chat", nonce: "n" }, privateKey);

    const parts = jwt.split(".");
    expect(parts).toHaveLength(3);

    const header = JSON.parse(new TextDecoder().decode(base64UrlDecode(parts[0])));
    expect(header).toEqual({ alg: "ES256", typ: "JWT" });
  });

  it("signs r‖s, 64 bytes, rather than DER", () => {
    // JWS wants the raw pair. DER would be ~70 bytes and start with 0x30, and a
    // server verifying it would reject every assertion this client sends.
    const { privateKey } = deriveLocalKeyPair(SEED, "gryt.chat");
    const jwt = signJwt({ a: 1 }, privateKey);
    expect(base64UrlDecode(jwt.split(".")[2])).toHaveLength(64);
  });

  it("verifies against the matching public key", () => {
    const { privateKey, publicJwk } = deriveLocalKeyPair(SEED, "gryt.chat");
    const jwt = signJwt({ iss: "key:x", aud: "gryt.chat" }, privateKey);
    const [h, b, sig] = jwt.split(".");

    expect(verifyJwtSignature(`${h}.${b}`, base64UrlDecode(sig), publicJwk)).toBe(true);
  });

  it("does not verify against a different key", () => {
    const mine = deriveLocalKeyPair(SEED, "gryt.chat");
    const theirs = deriveLocalKeyPair(SEED, "somewhere.else");
    const jwt = signJwt({ iss: "key:x" }, mine.privateKey);
    const [h, b, sig] = jwt.split(".");

    expect(verifyJwtSignature(`${h}.${b}`, base64UrlDecode(sig), theirs.publicJwk)).toBe(false);
  });

  it("does not verify a tampered payload", () => {
    const { privateKey, publicJwk } = deriveLocalKeyPair(SEED, "gryt.chat");
    const jwt = signJwt({ aud: "gryt.chat" }, privateKey);
    const [h, , sig] = jwt.split(".");
    const forged = base64Url(utf8(JSON.stringify({ aud: "evil.example" })));

    expect(verifyJwtSignature(`${h}.${forged}`, base64UrlDecode(sig), publicJwk)).toBe(false);
  });

  it("treats a malformed key as a failed verification rather than throwing", () => {
    expect(
      verifyJwtSignature("a.b", new Uint8Array(64), {
        kty: "EC",
        crv: "P-256",
        x: "!!!",
        y: "!!!",
      }),
    ).toBe(false);
  });
});

describe("the local certificate and assertion", () => {
  /* `getLocalIdentity` reads the Keychain, so these build the identity by hand
   * from the same pieces rather than mocking a native module — what is being
   * checked is the shape of what gets signed, and that is pure. */
  it("puts the public key in the certificate and nothing secret", () => {
    const { privateKey, publicJwk } = deriveLocalKeyPair(SEED, "gryt.chat");
    const identity = buildLocalIdentity(publicJwk, privateKey);

    const cert = JSON.parse(
      new TextDecoder().decode(base64UrlDecode(identity.certificate.split(".")[1])),
    );
    expect(cert.iss).toBe("gryt:self");
    expect(cert.sub).toBe(`key:${VECTORS[1].thumbprint}`);
    expect(cert.jwk).toEqual(publicJwk);
    // The private scalar has no business in a certificate.
    expect(cert.jwk.d).toBeUndefined();
    expect(identity.certificate).not.toContain(base64Url(privateKey));

    const assertion = signAssertion(identity, "gryt.chat", "nonce-from-server");
    const payload = JSON.parse(
      new TextDecoder().decode(base64UrlDecode(assertion.split(".")[1])),
    );

    // `iss` carries the subject, not `sub` — the server falls back to it and
    // the desktop client signs it this way. Both have to agree.
    expect(payload.iss).toBe(`key:${VECTORS[1].thumbprint}`);
    expect(payload.aud).toBe("gryt.chat");
    expect(payload.nonce).toBe("nonce-from-server");
    expect(payload.exp - payload.iat).toBe(60);

    // Nothing derived from the private scalar may appear anywhere in it.
    expect(assertion).not.toContain(base64Url(privateKey));
    expect(payload.d).toBeUndefined();
  });

  it("signs an assertion the matching public key verifies", () => {
    const { privateKey, publicJwk } = deriveLocalKeyPair(SEED, "gryt.chat");

    const assertion = signAssertion(
      buildLocalIdentity(publicJwk, privateKey),
      "gryt.chat",
      "n",
    );
    const [h, b, sig] = assertion.split(".");

    expect(verifyJwtSignature(`${h}.${b}`, base64UrlDecode(sig), publicJwk)).toBe(true);
  });
});
