import { describe, expect, it } from "vitest";

import { fromHex, toHex } from "./encoding";
import { BACKUP_WORDS, seedToWords, wordsToSeed } from "./words";

/**
 * Generated by running the **desktop client's own `@scure/bip39`**, not this
 * code. A phrase written down from one client has to restore the same identity
 * on the other; if these ever disagree, somebody's backup does not work and
 * nothing says so.
 */
const VECTORS = [
  {
    hex: "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
    words:
      "absurd avoid scissors anxiety gather lottery category door army half long cage bachelor another expect people blade school educate curtain scrub monitor lady beyond",
  },
  {
    hex: "fffefdfcfbfaf9f8f7f6f5f4f3f2f1f0efeeedecebeae9e8e7e6e5e4e3e2e1e0",
    words:
      "zoo wave left wave question wise thank team visual panel round tide year ivory recipe later try elbow whale slim evolve vapor maple adapt",
  },
  {
    hex: "030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dc",
    words:
      "adapt explain ecology dinner glare old unfair empty expect road off suggest dash dolphin captain version oval census uncover inform arrest trash first nice",
  },
];

describe("seedToWords", () => {
  it.each(VECTORS)("matches the desktop client for $hex", ({ hex, words }) => {
    expect(seedToWords(fromHex(hex))).toBe(words);
  });

  it(`is always ${BACKUP_WORDS} words`, () => {
    for (const v of VECTORS) {
      expect(seedToWords(fromHex(v.hex)).split(" ")).toHaveLength(BACKUP_WORDS);
    }
  });

  it("refuses a seed the generator should never have produced", () => {
    expect(() => seedToWords(new Uint8Array(32))).toThrow(/generator is broken/);
    expect(() => seedToWords(new Uint8Array(16))).toThrow(/32 bytes/);
  });
});

describe("wordsToSeed", () => {
  it.each(VECTORS)("reads $hex back", ({ hex, words }) => {
    expect(toHex(wordsToSeed(words))).toBe(hex);
  });

  it("does not care about case or spacing, because people retype these", () => {
    const messy = `  ${VECTORS[0].words.toUpperCase().replace(/ /g, "   ")}  `;
    expect(toHex(wordsToSeed(messy))).toBe(VECTORS[0].hex);
  });

  it("rejects a swapped word, which is the point of the checksum", () => {
    // Two valid words in the wrong order. Without a checksum this would restore
    // a different identity and look like it had worked.
    const parts = VECTORS[0].words.split(" ");
    [parts[0], parts[1]] = [parts[1], parts[0]];
    expect(() => wordsToSeed(parts.join(" "))).toThrow(/mistyped or swapped/);
  });

  it("says how many words it got when the count is wrong", () => {
    expect(() => wordsToSeed("absurd avoid scissors")).toThrow(/That is 3 words/);
  });

  it("asks for something when given nothing", () => {
    expect(() => wordsToSeed("   ")).toThrow(/Enter your identity words/);
  });

  it("rejects a word that is not in the list", () => {
    const parts = VECTORS[0].words.split(" ");
    parts[5] = "banana";
    expect(() => wordsToSeed(parts.join(" "))).toThrow(/valid identity backup/);
  });

  it("round-trips whatever it produced", () => {
    const seed = fromHex(VECTORS[2].hex);
    expect(toHex(wordsToSeed(seedToWords(seed)))).toBe(VECTORS[2].hex);
  });
});
