/* Ask Android for the highest refresh rate the panel supports.
 *
 * iOS needs one Info.plist key and it is done. Android has no equivalent
 * switch: most devices give a full-screen app the panel's top rate on their
 * own, but plenty of OEM skins hold apps at 60 until the window asks for
 * something else. Asking is a `preferredDisplayModeId` on the window's layout
 * params, which means touching MainActivity.
 *
 * It has to be a config plugin rather than an edit to android/. This project
 * is Expo prebuild — the native directories are generated and gitignored, so a
 * hand edit survives exactly until the next `expo prebuild` and then vanishes
 * without anyone noticing the frame rate went back to 60.
 *
 * The mode is chosen by refresh rate *within the current resolution*, not by
 * refresh rate alone. supportedModes mixes resolutions, and several phones list
 * their highest refresh only on a lower-resolution mode — picking the fastest
 * mode outright would quietly drop the display to 1080p to win a benchmark
 * nobody asked for.
 */
const { withMainActivity } = require("@expo/config-plugins");

const METHOD = `
  /**
   * Ask for the fastest mode at the resolution we are already running.
   *
   * Added by plugins/withAndroidHighRefreshRate.js — edit that, not this file.
   * This directory is regenerated by \`expo prebuild\`.
   */
  private fun requestHighestRefreshRate() {
    val display = if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.R) {
      display
    } else {
      @Suppress("DEPRECATION")
      windowManager.defaultDisplay
    } ?: return

    val current = display.mode ?: return
    val best = display.supportedModes
      .filter {
        it.physicalWidth == current.physicalWidth &&
          it.physicalHeight == current.physicalHeight
      }
      .maxByOrNull { it.refreshRate }
      ?: return

    if (best.modeId == current.modeId) return

    window.attributes = window.attributes.apply {
      preferredDisplayModeId = best.modeId
    }
  }
`;

module.exports = function withAndroidHighRefreshRate(config) {
  return withMainActivity(config, (mod) => {
    if (mod.modResults.language !== "kt") {
      throw new Error(
        "withAndroidHighRefreshRate: MainActivity is not Kotlin. " +
          "The injected code is Kotlin, so this needs rewriting rather than silently skipping."
      );
    }

    let contents = mod.modResults.contents;

    if (contents.includes("requestHighestRefreshRate")) {
      return mod;
    }

    // Call it from onCreate, after super, so the window exists.
    const onCreate = /(override fun onCreate\(savedInstanceState: Bundle\?\) \{\n)([\s\S]*?\n)(\s*\})/;
    if (!onCreate.test(contents)) {
      throw new Error(
        "withAndroidHighRefreshRate: could not find onCreate in MainActivity. " +
          "The Expo template changed shape — fix the plugin rather than dropping the call."
      );
    }

    contents = contents.replace(onCreate, (_m, head, body, tail) => {
      return `${head}${body}    requestHighestRefreshRate()\n${tail}`;
    });

    // Append the helper as the last member of the class.
    const lastBrace = contents.lastIndexOf("}");
    contents = contents.slice(0, lastBrace) + METHOD + contents.slice(lastBrace);

    mod.modResults.contents = contents;
    return mod;
  });
};
