// Render every app icon asset from the two SVGs in assets/source. **The prebuild after
// it is not optional** — the asset catalogue under ios/ is generated by it.
import sharp from "sharp";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const assets = resolve(root, "assets");
const full = readFileSync(resolve(assets, "source/icon.svg"));
const face = readFileSync(resolve(assets, "source/icon-face.svg"));

/** The field the owl sits on. Matches the rect in icon.svg. */
const BG = "#2E2D5F";

// iOS, 1024, flattened opaque. App Store Connect rejects an icon with an alpha channel
// *after* the upload has transferred rather than before it starts.
await sharp(full).resize(1024, 1024).flatten({ background: BG }).png()
  .toFile(resolve(assets, "icon.png"));

// Android adaptive background: a flat field. The mark lives in the foreground
// layer because the launcher parallaxes the two against each other.
await sharp({ create: { width: 512, height: 512, channels: 4, background: BG } })
  .png().toFile(resolve(assets, "android-icon-background.png"));

// Android adaptive foreground, full-bleed rather than inset: the owl bleeds off the
// bottom, so the safe zone leaves a flat-cut belly floating in a square.
await sharp(face).resize(512, 512).png()
  .toFile(resolve(assets, "android-icon-foreground.png"));

// Themed icon. Android discards the colours, so only the alpha carries — forced white.
// The eyes and beak are punched out with dest-out; deleting them reveals the face.
const GROUND = "#2E2D5F";
const faceSvg = face.toString("utf8");
const featurePaths = faceSvg.match(new RegExp(`<path[^>]*fill="${GROUND}"[^>]*/>`, "gi")) ?? [];
if (featurePaths.length === 0) {
  throw new Error(`icon-face.svg: nothing painted ${GROUND} — the mark's palette moved`);
}
const featuresOnly = Buffer.from(
  `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">` +
    featurePaths.join("") +
    `</svg>`,
);

const MONO = 432;
const { data, info } = await sharp(face).resize(MONO, MONO).ensureAlpha()
  .raw().toBuffer({ resolveWithObject: true });
for (let i = 0; i < data.length; i += info.channels) {
  data[i] = 255;
  data[i + 1] = 255;
  data[i + 2] = 255;
}
await sharp(data, { raw: { width: info.width, height: info.height, channels: info.channels } })
  .composite([
    {
      input: await sharp(featuresOnly).resize(MONO, MONO).png().toBuffer(),
      blend: "dest-out",
    },
  ])
  .png().toFile(resolve(assets, "android-icon-monochrome.png"));

await sharp(full).resize(48, 48).png().toFile(resolve(assets, "favicon.png"));

// Splash: the mark on transparency, so it sits on whatever the splash
// background is rather than carrying its own dark square into the middle of it.
await sharp(face).resize(1024, 1024).png().toFile(resolve(assets, "splash-icon.png"));

console.log("icons: 6 written to assets/");
