// Render every app icon asset from the two SVGs in assets/source.
//
// One source in, six PNGs out, so the set can be regenerated when a size or a
// platform requirement changes rather than being hand-exported once and left to
// drift. Run it after editing either SVG:
//
//   node scripts/icons.mjs && npx expo prebuild --platform ios
//
// The prebuild is not optional. `expo run:ios` does not pick up an icon change
// — the asset catalogue under ios/ is generated by prebuild, so without it the
// app keeps whatever icon it was built with and nothing says otherwise.
import sharp from "sharp";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const assets = resolve(root, "assets");
const full = readFileSync(resolve(assets, "source/icon.svg"));
const face = readFileSync(resolve(assets, "source/icon-face.svg"));

/** The field the owl sits on. Matches the rect in icon.svg. */
const BG = "#2E2D5F";

// iOS, 1024, flattened opaque. App Store Connect rejects an icon with an alpha
// channel, and it rejects it *after* the upload has transferred rather than
// before it starts.
await sharp(full).resize(1024, 1024).flatten({ background: BG }).png()
  .toFile(resolve(assets, "icon.png"));

// Android adaptive background: a flat field. The mark lives in the foreground
// layer because the launcher parallaxes the two against each other.
await sharp({ create: { width: 512, height: 512, channels: 4, background: BG } })
  .png().toFile(resolve(assets, "android-icon-background.png"));

// Android adaptive foreground, full-bleed rather than inset into the safe zone.
//
// Insetting is the usual advice and is wrong for this artwork. The owl is drawn
// to bleed off the bottom of its artboard, so scaling it down to fit the safe
// zone puts a flat-cut belly floating in the middle of a transparent square,
// which reads as a rendering bug rather than as a crop. Full-bleed lets the
// launcher's mask do the cropping — the same job iOS's rounded corners do — and
// both platforms then show the same owl.
await sharp(face).resize(512, 512).png()
  .toFile(resolve(assets, "android-icon-foreground.png"));

// Themed icon. Android discards the colours and recolours the silhouette, so
// only the alpha carries information. Forced to solid white for that reason: a
// greyscale pass was tried first and left a pale owl that the theming then
// washed out to nothing.
//
// The eyes and beak are punched out of the alpha, and that is new. It cannot be
// done by deleting those paths: they are opaque shapes drawn *over* an opaque
// face, so removing them only reveals the face underneath and the result is the
// same blank silhouette. They have to be composited out — rendered on their own
// and subtracted, which is what dest-out does.
//
// Worth it because the old mark could not have this at all. Its features were
// light shapes on a dark bird, so there was nothing to subtract that would read
// as a face; the 2026 mark paints all three in the ground's own colour, which
// is what makes them holes in the drawing and now holes in the alpha too.
//
// Only this pass. The same file feeds the Android foreground and the splash,
// where the features are meant to be visible as dark shapes.
const GROUND = "#2E2D5F";
const faceSvg = face.toString("utf8");
const featurePaths = faceSvg.match(new RegExp(`<path[^>]*fill="${GROUND}"[^>]*/>`, "gi")) ?? [];
if (featurePaths.length === 0) {
  throw new Error(`icon-face.svg: nothing painted ${GROUND} — the mark's palette moved`);
}
const featuresOnly = Buffer.from(
  `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">` +
    featurePaths.join("") +
    `</svg>`,
);

const MONO = 432;
const { data, info } = await sharp(face).resize(MONO, MONO).ensureAlpha()
  .raw().toBuffer({ resolveWithObject: true });
for (let i = 0; i < data.length; i += info.channels) {
  data[i] = 255;
  data[i + 1] = 255;
  data[i + 2] = 255;
}
await sharp(data, { raw: { width: info.width, height: info.height, channels: info.channels } })
  .composite([
    {
      input: await sharp(featuresOnly).resize(MONO, MONO).png().toBuffer(),
      blend: "dest-out",
    },
  ])
  .png().toFile(resolve(assets, "android-icon-monochrome.png"));

await sharp(full).resize(48, 48).png().toFile(resolve(assets, "favicon.png"));

// Splash: the mark on transparency, so it sits on whatever the splash
// background is rather than carrying its own dark square into the middle of it.
await sharp(face).resize(1024, 1024).png().toFile(resolve(assets, "splash-icon.png"));

console.log("icons: 6 written to assets/");
