// Render every app icon asset from the two SVGs in assets/source.
//
// One source in, six PNGs out, so the set can be regenerated when a size or a
// platform requirement changes rather than being hand-exported once and left to
// drift. Run it after editing either SVG:
//
//   node scripts/icons.mjs && npx expo prebuild --platform ios
//
// The prebuild is not optional. `expo run:ios` does not pick up an icon change
// — the asset catalogue under ios/ is generated by prebuild, so without it the
// app keeps whatever icon it was built with and nothing says otherwise.
import sharp from "sharp";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const assets = resolve(root, "assets");
const full = readFileSync(resolve(assets, "source/icon.svg"));
const face = readFileSync(resolve(assets, "source/icon-face.svg"));

/** The field the owl sits on. Matches the rect in icon.svg. */
const BG = "#0D0E12";

// iOS, 1024, flattened opaque. App Store Connect rejects an icon with an alpha
// channel, and it rejects it *after* the upload has transferred rather than
// before it starts.
await sharp(full).resize(1024, 1024).flatten({ background: BG }).png()
  .toFile(resolve(assets, "icon.png"));

// Android adaptive background: a flat field. The mark lives in the foreground
// layer because the launcher parallaxes the two against each other.
await sharp({ create: { width: 512, height: 512, channels: 4, background: BG } })
  .png().toFile(resolve(assets, "android-icon-background.png"));

// Android adaptive foreground, full-bleed rather than inset into the safe zone.
//
// Insetting is the usual advice and is wrong for this artwork. The owl is drawn
// to bleed off the bottom of its artboard, so scaling it down to fit the safe
// zone puts a flat-cut belly floating in the middle of a transparent square,
// which reads as a rendering bug rather than as a crop. Full-bleed lets the
// launcher's mask do the cropping — the same job iOS's rounded corners do — and
// both platforms then show the same owl.
await sharp(face).resize(512, 512).png()
  .toFile(resolve(assets, "android-icon-foreground.png"));

// Themed icon. Android discards the colours and recolours the silhouette, so
// only the alpha carries information. Forced to solid white for that reason: a
// greyscale pass was tried first and left a pale owl that the theming then
// washed out to nothing.
const { data, info } = await sharp(face).resize(432, 432).ensureAlpha()
  .raw().toBuffer({ resolveWithObject: true });
for (let i = 0; i < data.length; i += info.channels) {
  data[i] = 255;
  data[i + 1] = 255;
  data[i + 2] = 255;
}
await sharp(data, { raw: { width: info.width, height: info.height, channels: info.channels } })
  .png().toFile(resolve(assets, "android-icon-monochrome.png"));

await sharp(full).resize(48, 48).png().toFile(resolve(assets, "favicon.png"));

// Splash: the mark on transparency, so it sits on whatever the splash
// background is rather than carrying its own dark square into the middle of it.
await sharp(face).resize(1024, 1024).png().toFile(resolve(assets, "splash-icon.png"));

console.log("icons: 6 written to assets/");
